# deploy_production:
#   stage: deploy
#   image: docker:stable
#   services:
#     - docker:dind
#   tags:
#     - production
#   only:
#     refs:
#     - tags
#     - triggers
#     - master
#   when: manual
#   before_script:
#     - docker info
#     - apk add --no-cache docker-compose
#   script:
#     - docker-compose up -d
